[workspace]
resolver = "2"
members = ["crates/*", "src-tauri"]

[workspace.package]
version = "0.1.0"
edition = "2021"
repository = "https://github.com/hnam0212/cricket"

[workspace.dependencies]
cricket-core = { path = "crates/cricket-core" }
cricket-audio-win = { path = "crates/cricket-audio-win" }
